require("noctalia")

require("hyprland.monitors")
require("hyprland.autostart")
require("hyprland.environment")
require("hyprland.permissions")
require("hyprland.appearance")
require("hyprland.input")
require("hyprland.binds")
require("hyprland.rules")
